#+title: Screamer - A Nondeterministic Programming Library

Screamer is an extension of Common Lisp that adds support for nondeterministic
programming. Screamer consists of two levels. The basic nondeterministic level
adds support for backtracking and undoable side effects. On top of this
nondeterministic substrate, Screamer provides a comprehensive constraint
programming language in which one can formulate and solve mixed systems of
numeric and symbolic constraints. Together, these two levels augment Common
Lisp with practically all of the functionality of both Prolog and constraint
logic programming languages such as CHiP and CLP(R). Furthermore, Screamer is
fully integrated with Common Lisp. Screamer programs can coexist and
interoperate with other extensions such as CLIM and Iterate.

In several ways Screamer is more efficient than other implementations of
backtracking languages. First, Screamer code is transformed into Common Lisp
which can be compiled by the underlying Common Lisp system. Many competing
implementations of nondeterministic Lisp are interpreters and thus are far
less efficient than Screamer. Second, the backtracking primitives require
fairly low overhead in Screamer. Finally, this overhead to support
backtracking is only paid for by those portions of the program which use the
backtracking primitives. Deterministic portions of user programs pass through
the Screamer-to-Common-Lisp transformation unchanged. Since in practise, only
small portions of typical programs utilize the backtracking primitives,
Screamer can produce more efficient code than compilers for languages in which
backtracking is more pervasive.

Screamer was originally written by Jeffrey Mark Siskind and David Allen McAllester,
see file LICENSE for licensing information.

* Examples
See http://nikodemus.github.io/screamer/ for some examples of the core Screamer
functionality.
* Version history
** 5.1.1
- Minor incompatible changes to ~sample~ function signature
- Added ~sample-once~ as a means of sampling without any impact to backtracking
** 5.1.0
- Incompatible API change to ~n-values~ and ~ith-value~, enclosing the configuration at the
  beginning of the form. This allows you to run multiple forms within the body of these
  constructs, and permits extending the construct with more configurations later on.
** 5.0.0
Extension of the library to support probabilistic programming, as well as
some more utility functions.

Fixes for some scenarios that previously led to incorrect results or infinite
searches.

Some new utility functions (e.g. ~with-trail~).

Significant refactoring and some memory-oriented optimizations.
** 4.0.0
Publicly maintained version of Screamer under MIT license. Kudos to @nikodemus
for his efforts in maintaining and documenting the library.

See the ~4_0~ files in ~/docs~ for more info about this version.
** 3.20
Last version of the original Screamer
